---
qdr_dns_servers: 10.19.110.3
qdr_image: quay.io/interconnectedcloud/qdrouterd
qdr_image_tag: 1.5.0
qdr_config_files: /opt/qdrouterd/etc

router:
    id_prefix: BAROMETER_ROUTER
    mode: interior

listeners:
    - host: 0.0.0.0
      port: 5672
    - host: 0.0.0.0
      port: 5673

connectors:
    - name: central-qdr
      role: edge
      host: qdr-white-normal-sa-telemetry.apps.dev7.nfvpe.site
      port: 443
